import type { Metadata } from "next";
import { Inter, JetBrains_Mono, Nunito, Montserrat } from "next/font/google";
import "./globals.css";
import RootProvider from "@/components/layout-providers/RootProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Custom Widgets | TapDay ",
  description: "Generated by create next app",
  // Define the favicon link here:
  // icons: {
  
  //       // Use the relative path to the public directory
  //       url: "/custom-favicon.svg", // ensure the file is in /public and referenced from root
  //       type: "image/svg+xml",
   
  //   // You can also add a traditional .ico fallback if needed
  //   // shortcut: '/favicon.ico',
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon" // use the correct rel
          href="/favicon.ico" // served from /public
          sizes="any" // use the correct sizes
        />
      </head>
      <body
        // Use Nunito globally
        // className={`${nunito.className} ${inter.className} ${jetbrainsMono.className} ${montserrat.className} antialiased`}
        className={` ${inter.className} antialiased`}
      >
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
