import type { Metadata } from "next";
import { Inter, JetBrains_Mono, Nunito, Montserrat } from "next/font/google";
import "./globals.css";
import RootProvider from "@/components/layout-providers/RootProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // Use Nunito globally
        // className={`${nunito.className} ${inter.className} ${jetbrainsMono.className} ${montserrat.className} antialiased`}
        className={` ${inter.className} antialiased`}
      >
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
